apiVersion: v1
kind: Secret
metadata:
  name: reconciliation-secret
type: Opaque
data:
  # THIS FILE IS A TEMPLATE - IT WILL BE OVERWRITTEN BY THE CD WORKFLOW
  # The CD workflow will automatically:
  # 1. Read secrets from GitHub repository secrets
  # 2. Encode them to base64
  # 3. Create this file with the encoded values
  # 4. Apply it to Kubernetes
  
  # Do not manually edit this file - it will be regenerated on every deployment
  
  # Placeholder values (will be replaced by CD workflow)
  ACTIVITY_SERVICE_URL: ""
  PATIENT_SERVICE_URL: ""
  SCHEDULER_SERVICE_URL: ""
  RABBITMQ_URL: ""
